django_todo/urls.py
from django.contrib import admin
from django.urls import path
# importing views where we write our functions
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),  # default admin path [CHANGE URL TO KEEP IT SAFE]
    path('', views.get_todo_list, name='get_todo_list'),
    path('add', views.add_item, name='add'),
    # these need the item_id as they access the items data from db
    path('edit/<item_id>', views.edit_item, name='edit'),
    path('toggle/<item_id>', views.toggle_item, name='toggle'),
    path('delete/<item_id>', views.delete_item, name='delete'),
]

todo/models.py
from django.db import models

# Create your models here (models = our db design/layout)
# class => django creates a table after migrations


class Item(models.Model):  # inheriting Django's base Model class
    name = models.CharField(max_length=50, null=False, blank=False)
    done = models.BooleanField(null=False, blank=False, default=False)

    # redefining how our items will be named in the db
    def __str__(self):
        return self.name

todo/forms.py
# inorder to control and manage form functionality with Django
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:  # info about itself/how to render etc
        model = Item
        fields = ['name', 'done']

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Item
from .forms import ItemForm

# Create your views here.


def get_todo_list(request):
    items = Item.objects.all()
    # context => data that needs to be used in the rendered template
    context = {
        'items': items
    }
    return render(request, 'todo/todo_list.html', context)  # returns a HttpResponse


def add_item(request):
    # the POST handler
    if request.method == 'POST':
        # getting the info from the form
        form = ItemForm(request.POST)
        if form.is_valid():
            form.save()
            # calling the function to return to home
            return redirect('get_todo_list')
    # using forms.py
    form = ItemForm()
    context = {
        'form': form
    }
    return render(request, 'todo/add_item.html', context)  # returns a HttpResponse


def edit_item(request, item_id):
    # getting the item from the db
    item = get_object_or_404(Item, id=item_id)
    # the POST handler
    if request.method == 'POST':
        # getting the info from the form
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('get_todo_list')
    # specifying the data the form should be pre-popped with
    form = ItemForm(instance=item)
    context = {
        'form': form
    }
    return render(request, 'todo/edit_item.html', context)


def toggle_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    item.done = not item.done  # switching its done status
    item.save()
    return redirect('get_todo_list')


def delete_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    item.delete()  # deleting the item
    return redirect('get_todo_list')

todo/templates/todo/add_item.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Add Item</title>
    </head>
    <body>
        <h1>Add a ToDo Item:</h1>
        <form method="POST" action="add">  <!-- submitting the form to our 'add' url -->
            {% csrf_token %} <!-- randomly generated hidden input to varify the form data is coming from our app -->

            <!-- genertaing the form using form.py instead -->
            <!-- id => to target with CSS, name => to target the value within our views function -->
            <!-- <div>
                <p>
                    <label for="id_name">Name: </label>
                    <input type="text" id="id_name" name="item_name">
                </p>
            </div>
            <div>
                <p>
                    <label for="id_done">Done: </label>
                    <input type="checkbox" id="id_done" name="done">
                </p>
            </div> -->

            <!-- .as_p => 'as paragraphs' for vertical layout -->
            {{ form.as_p }}
            <div>
                <p>
                    <button type="submit">Add Item</button>
                </p>
            </div>
        </form>
    
    </body>
</html>

todo/templates/todo/edit_item.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Edit Item</title>
    </head>
    <body>
        <h1>Edit a ToDo Item:</h1>
        <form method="POST">  <!-- no action => posts to current url -->
            {% csrf_token %} <!-- randomly generated hidden input to varify the form data is coming from our app -->
            <!-- .as_p => 'as paragraphs' for vertical layout -->
            {{ form.as_p }}
            <div>
                <p>
                    <button type="submit">Update Item</button>
                </p>
            </div>
        </form>
    
    </body>
</html>

todo/templates/todo/todo_list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Todo List</title>
    </head>
    <body>
        <h1>Things i need to do:</h1>

        <table>
            {% for item in items %}
                <tr>
                    {% if item.done %}
                        <td><strike>{{ item.name }}</strike></td>
                    {% else  %}
                        <td>{{ item.name }}</td>
                    {% endif %}
                    <!-- done status toggle -->
                    <td>
                        <a href="/toggle/{{ item.id }}">
                            <button>Toggle</button>
                        </a>
                    </td>
                    <!-- edit button -->
                    <td>
                        <a href="/edit/{{ item.id }}">
                            <button>Edit</button>
                        </a>
                    </td>
                    <!-- delete button -->
                    <td>
                        <a href="/delete/{{ item.id }}">
                            <button>Delete</button>
                        </a>
                    </td>
                </tr>
            {% empty %}  <!-- incase the db is empty -->
            <tr>
                <td>You have nothing to do</td>
            </tr>
            {% endfor %}
        </table>
        <a href="/add">Add and Item</a>
    
    </body>
</html>